# Урок 2 Матрицы и операции над ними

In [139]:
import numpy as np
from pprint import pprint as pp

## Часть 1

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Решение.
- а) не определены
- б) определено АВ, размерность 2 на 3
- в) определены оба, dim(АВ) = 8x8, dim(BA) = 3x3
- г) определены оба, размерность 4x4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$ A + B = 
\begin{pmatrix}
5 & -3\\
3 & 5
\end{pmatrix} $$

In [140]:
A = np.array([[1,-2], [3,0]])
B = np.array([[4,-1], [0,5]])
pp(A)
pp(B)
pp(A + B)

array([[ 1, -2],
       [ 3,  0]])
array([[ 4, -1],
       [ 0,  5]])
array([[ 5, -3],
       [ 3,  5]])


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$ 3A -2B + 4C =  \begin{pmatrix} 3 & 21 \\ 9 & -18 \end{pmatrix} + 
\begin{pmatrix} 0 & -10 \\ -4 & 2 \end{pmatrix} +
\begin{pmatrix} 8 & -16 \\ 4 & 4 \end{pmatrix} = 
\begin{pmatrix} 11 & -5 \\ 9 & -12 \end{pmatrix}$$

In [141]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$$ AA^T = \begin{pmatrix} 17 & 18 & 11 \\ 18 & 29 & 4 \\ 11 & 4 & 13 \end{pmatrix} $$
$$ A^TA = \begin{pmatrix} 45 & 0 \\ 0 & 14 \end{pmatrix} $$

In [142]:
A = np.array([[4, 1], [5, -2], [2, 3]])
pp(A)
pp(A.dot(A.T))
pp(A.T.dot(A))

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])
array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])
array([[45,  0],
       [ 0, 14]])


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [143]:
# Перемножает две матрицы; по честному надо три цикла, но последний тривиален, поэтому - два
def dot(A, B):
    N = A.shape[0]
    M = A.shape[1]
    M_ = B.shape[0]
    assert(M == M_) # условие сцепления
    P = B.shape[1]
    out = np.zeros((N, P))
    for i in range(N):
        for j in range(P):
            out[i, j] = np.dot(A[i,:], B[:,j]) # поэлементная сумма произведений
    return out

In [144]:
B = dot(A, A.T)

In [145]:
B

array([[ 17.000,  18.000,  11.000],
       [ 18.000,  29.000,  4.000],
       [ 11.000,  4.000,  13.000]])

In [146]:
C = dot(A.T, A)

In [147]:
C

array([[ 45.000,  0.000],
       [ 0.000,  14.000]])

## Часть 2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

- а)
$ \sin^2 + \cos^2 x = 1 $
- б)
$ 4 \cdot 5 \cdot 9 = 180 $
- в)
$ 1 \cdot (5 \cdot 9 - 6 \cdot 8) - 2 \cdot (4 \cdot 9 - 7 \cdot 6) + 3 \cdot (4 \cdot 8 - 7 \cdot 5) =
-3 + 12 - 9 = 0
$

In [148]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print('A = ')
pp(A)
print('det(A) = {:f}'.format(np.linalg.det(A)))
print('')
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('B = ')
pp(B)
print('det(B) = {:f}'.format(np.linalg.det(B)))

A = 
array([[4, 2, 3],
       [0, 5, 1],
       [0, 0, 9]])
det(A) = 180.000000

B = 
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
det(B) = 0.000000


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

- а)
$ \det(A^2) = \det(A \cdot A) = \det(A) \cdot \det(A) = 4 \cdot 4 = 16 $
- б)
$ \det(A^T) = \det(A) = 4 $
- в)
$ \det(2A) = \det(2E) \cdot \det(A) = 2^3 \cdot 4 = 32 $,
потому что $2 = 2 \cdot 1 = 2E$, где $E$ - единичная матрица (матрица-единица). Умножение двойки на матрицу можно записать в общем виде как произведение двух матриц и дальше использовать свойство определителя произведения.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Так как удвоенная первая строка равна второй, взятой с противоположным знаком, то эти строки линейно зависимы и, значит, определитель такой матрицы равен нулю. Отсюда вывод - матрица вырождена.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

- а) Выделим в матрице "костяк" ("скелет")

$ 
{} \equiv \begin{pmatrix} 0 & 1 & 2 \\ 1 & 1 & 1 \\ 0 & 1 & 2 \end{pmatrix}
\equiv {...}
\equiv \begin{pmatrix} 0 & 0 & 0 \\ 1 & 0 & 0 \\ 0 & 1 & 0 \end{pmatrix}
$

Вывод: ранг равен двум, так как можно найти ненулевой определитель "два на два", а "три на три" - нет.

-б)
Ранг равен трем, так как определитель матрицы "три на три", стоящей в правом нижнем углу исходной матрицы, отличен от нуля, а определитель исходной равен нулю (легко вычисляется раскладыванием по первому столбцу).