# Урок 5 Сингулярное разложение матриц

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [39]:
import numpy as np
np.set_printoptions(suppress=True)

1.

In [40]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
U, d, W = np.linalg.svd(A)
V = W.T
print(U)
print()
print(V)
print()
print(d)

[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]

[[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]

[8.82486885 6.14060608 2.53271528]


In [41]:
print(A.shape)
print(U.shape)
print(V.shape)

(5, 3)
(5, 5)
(3, 3)


In [42]:
D = np.zeros((A.shape[0], A.shape[1]))

In [43]:
D.shape

(5, 3)

In [44]:
D[np.diag_indices(min(A.shape))] = d
DV = np.dot(D, V.T)

In [45]:
DV

array([[ 0.62801746,  6.32764871,  6.11921287],
       [-2.25592504,  4.08436776, -3.99196508],
       [-2.34870098, -0.52801681,  0.7870506 ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [46]:
Ae = np.dot(U, DV)

In [47]:
Ae

array([[ 1.,  2.,  0.],
       [ 0., -0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [-0.,  1.,  0.]])

In [48]:
D

array([[8.82486885, 0.        , 0.        ],
       [0.        , 6.14060608, 0.        ],
       [0.        , 0.        , 2.53271528],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [49]:
A - Ae

array([[ 0., -0., -0.],
       [-0.,  0.,  0.],
       [-0.,  0., -0.],
       [ 0., -0., -0.],
       [ 0., -0., -0.]])

2.

In [50]:
L2 = d[0]

In [51]:
Lf = np.sqrt(d.dot(d))

In [57]:
print(f'Евклидова норма матрицы A {L2}')

Евклидова норма матрицы A 8.824868854820444


In [58]:
print(f'Норма Фробениуса матрицы A {Lf}')

Норма Фробениуса матрицы A 11.045361017187263
