# Урок 4 Системы линейных уравнений

## Часть 1

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Запишем расширенную матрицу данной СЛАУ
$$ \begin{pmatrix} 1 & 1 & -1 & -2 & 0 \\ 2 & 1 & -1 & 1 & -2 \\ 1 & 1 & -3 & 1 & 4 \end{pmatrix} $$

Далее последовательно приведем ее к нижне-треугольному виду
$$
\begin{pmatrix} 1 & 1 & -1 & -2 & 0 \\ 0 & -1 & 1 & 5 & -2 \\ 1 & 1 & -3 & 1 & 4 \end{pmatrix} \equiv
\begin{pmatrix} 1 & 1 & -1 & -2 & 0 \\ 0 & -1 & 1 & 5 & -2 \\ 0 & 0 & -2 & 3 & 4 \end{pmatrix} \equiv
\begin{pmatrix} 1 & 1 & -1 & -2 & 0 \\ 0 & -1 & 1 & 5 & -2 \\ 0 & 0 & -2 & 3 & 4 \end{pmatrix}
$$

По ненулевому определителю крайней левой подматрицы 3x3 видно, что ранг основной матрицы равен рангу расширенной и равен 3, что меньше числа неизвестных 4, поэтому данная система имеет бесконечно много решений. Для удобства добьемся как можно большего количества нулей расширенной матрицы:

$$ \begin{pmatrix} 1 & 1 & -1 & -2 & 0 \\ 0 & -1 & 1 & 5 & -2 \\ 0 & 0 & -2 & 3 & 4 \end{pmatrix} \equiv
\begin{pmatrix} 1 & 0 & 0 & 3 & -2 \\ 0 & -1 & 1 & 5 & -2 \\ 0 & 0 & -2 & 3 & 4 \end{pmatrix} \equiv\begin{pmatrix} 1 & 0 & 0 & 3 & -2 \\ 0 & -2 & 0 & 13 & 0 \\ 0 & 0 & -2 & 3 & 4 \end{pmatrix}
$$

В итоге получаем общее решение:

$$ \vec{v} = -2 \cdot (1,0,1,0) + c \cdot (-6, 13, 3, 2), ~c \in \mathbb{R}. $$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

Запишем расширенную матрицу и методом Гаусса определим ранги расширенной и основной матрицы.
- а)
$$ \begin{pmatrix} 1 & 1 & -1 & 0 \\ 2 & -5 & -3 & -17 \\ 3 & -1 & 1 & 4 \end{pmatrix} \equiv
\begin{pmatrix} 1 & 1 & -1 & 0 \\ 0 & -7 & -1 & -17 \\ 3 & -1 & 1 & 4 \end{pmatrix} \equiv
\begin{pmatrix} 1 & 1 & -1 & 0 \\ 0 & -7 & -1 & -17 \\ 0 & -4 & 4 & 4 \end{pmatrix} \equiv
\begin{pmatrix} 1 & 1 & -1 & 0 \\ 0 & -7 & -1 & -17 \\ 0 & 0 & 32 & 96 \end{pmatrix}
$$

Видно, что ранг основной матрицы равен 3 и равен рангу расширенной матрицы и совпадает с числом неизвестных 3, поэтому данная СЛАУ имеет единственное решение $$\vec{v} = (1, 2, 3)$$
- б)
$$ \begin{pmatrix} 1 & -2 & 3 & -2 \\ 2 & -4 & 6 & 1 \\ 3 & -6 & 9 & 5 \end{pmatrix} \equiv
\begin{pmatrix} 1 & -2 & 3 & -2 \\ 0 & 0 & 0 & 5 \\ 3 & -6 & 9 & 5 \end{pmatrix} \equiv
\begin{pmatrix} 1 & -2 & 3 & -2 \\ 0 & 0 & 0 & 5 \\ 0 & 0 & 0 & 11 \end{pmatrix}
$$

Видно, что ранг основной матрицы равен 1, а ранг расширенной равен 2, поэтому СЛАУ несовместная.

- в)
$$ \begin{pmatrix} 1 & 2 & 5 & 4 \\ 3 & 1 & -8 & -2 \end{pmatrix} \equiv
\begin{pmatrix} 1 & 2 & 5 & 4 \\ 0 & -5 & -23 & -14 \end{pmatrix}
$$

Видно, что ранг основной матрицы равен рангу расширенной и равен 2, но меньше числа неизвестных 3, поэтому СЛАУ имеет бесконечно много решений $$ \vec{v} = -\frac{2}{5} \cdot (4, -7, 0) + c \cdot (21, -23, 5), ~c \in \mathbb{R}. $$

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

Видно, что ранг основной матрицы равен рангу расширенной матрицы и совпадает с числом неизвестных 4, значит СЛАУ совместна и имеет единственное решение.

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

СЛАУ будет несовместной тогда и только тогда, когда ранг основной матрицы будет меньше ранга расширенной. В нашем случае ранг основной матрицы равен 2 (вспомним нулевой определитель матрицы из [[1,2,3],[4,5,6],[7,8,9]], значит для несовместности СЛАУ достаточно сделать ранг расширенной равным 3. Если (a, b, c) взять пропорционально любому столбцу основной матрицы, то определитель любой подматрицы 3x3, содержащей столбец (a, b, c), будет нулевым и потому ранг расширенной меньше 3. Значит, для несовместности столбец (a, b, c) должен быть линейно-независимым от столбцов основной матрицы (любые два столбца основной матрицы линейно-независимы). Для отыскания такой конфигурации запишем определитель, взяв первые два столбца основной матрицы:

$$ \begin{vmatrix} 1 & 2 & a \\ 4 & 5 & b \\ 7 & 8 & c \end{vmatrix} \neq 0$$

Преобразуем определитель, учитывая, что для сравнения с нулем не играет роли константа перед определителем:
$$ \begin{vmatrix} 1 & 2 & a \\ 4 & 5 & b \\ 7 & 8 & c \end{vmatrix} \equiv
\begin{vmatrix} 1 & 0 & a \\ 4 & -3 & b \\ 7 & -6 & c \end{vmatrix} \equiv
\begin{vmatrix} 3 & 0 & a \\ 0 & -3 & b \\ -3 & -6 & c \end{vmatrix} \equiv
\begin{vmatrix} 1 & 0 & a \\ 0 & 1 & b \\ -1 & 2 & c \end{vmatrix} \equiv 
\begin{vmatrix} 1 & 0 & a \\ 0 & 1 & b \\ 0 & 2 & a + c \end{vmatrix}
\neq 0
$$

Отсюда следует искомое условие:
$$ b \neq \frac{a+c}{2} $$

## Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

- а)
$$ A = \begin{pmatrix} 1 & -2 \\ 3 & -4 \end{pmatrix}$$

$$ \det{A} = \begin{vmatrix} 1 & -2 \\ 3 & -4 \end{vmatrix} = -4 + 6 = 2 $$

$$ det{A_1} =  \begin{vmatrix} 1 & -2 \\ 7 & -4 \end{vmatrix} = -4 + 14 = 10 $$

$$ det{A_2} =  \begin{vmatrix} 1 & 1 \\ 3 & 7 \end{vmatrix} = 7 - 3 = 4 $$

$$ x_1 = \frac{\det {A_1} }{ \det{A} } = 10 / 2 = 5 $$

$$ x_2 = \frac{\det {A_2} }{ \det{A} } = 4 / 2 = 2 $$

- б)
$$ A = \begin{pmatrix} 2 & -1 & 5 \\ 1 & 1 & -3 \\ 2 & 4 & 1 \end{pmatrix} $$

$$ \det{A} = \begin{vmatrix} 2 & -1 & 5 \\ 1 & 1 & -3 \\ 2 & 4 & 1 \end{vmatrix} = 43 $$

$$ \det{A_1} = \begin{vmatrix} 10 & -1 & 5 \\ -2 & 1 & -3 \\ 1 & 4 & 1 \end{vmatrix} = 86 $$

$$ \det{A_2} = \begin{vmatrix} 2 & 10 & 5 \\ 1 & -2 & -3 \\ 2 & 1 & 1 \end{vmatrix} = -43 $$

$$ \det{A_3} = \begin{vmatrix} 2 & -1 & 10 \\ 1 & 1 & -2 \\ 2 & 4 & 1 \end{vmatrix} = 43 $$

$$ x_1 = \frac{\det {A_1} }{ \det{A} } = 86 / 43 = 2 $$

$$ x_2 = \frac{\det {A_2} }{ \det{A} } = -43 / 43 = -1 $$

$$ x_3 = \frac{\det {A_3} }{ \det{A} } = 43 / 43 = 1 $$

__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

- а)
$$ \begin{pmatrix} 1 & 2 & 4 \\ 2 & 9 & 12 \\ 3 & 26 & 30 \end{pmatrix} \equiv 
\begin{pmatrix} 1 & 2 & 4 \\ 0 & 5 & 4 \\ 0 & 20 & 18 \end{pmatrix} \equiv 
\begin{pmatrix} 1 & 2 & 4 \\ 0 & 5 & 4 \\ 0 & 0 & 2 \end{pmatrix}
$$

Первый шаг дает коэффициенты ${m}_{i1} = (2, 3)$. Второй шаг дает коэффициенты ${m}_{i2} = (4)$, поэтому L-матрица будет следующей:

$$ L = \begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 0 \\ 3 & 4 & 1 \end{pmatrix} $$

- б)
$$ \begin{pmatrix} 1 & 1 & 2 & 4 \\ 2 & 5 & 8 & 9 \\ 3 & 18 & 29 & 18 \\ 4 & 22 & 53 & 33 \end{pmatrix} \equiv 
\begin{pmatrix} 1 & 1 & 2 & 4 \\ 0 & 3 & 4 & 1 \\ 0 & 15 & 23 & 6 \\ 0 & 18 & 45 & 17 \end{pmatrix} \equiv 
\begin{pmatrix} 1 & 1 & 2 & 4 \\ 0 & 3 & 4 & 1 \\ 0 & 0 & 3 & 1 \\ 0 & 0 & 21 & 11 \end{pmatrix} \equiv 
\begin{pmatrix} 1 & 1 & 2 & 4 \\ 0 & 3 & 4 & 1 \\ 0 & 0 & 3 & 1 \\ 0 & 0 & 0 & 4 \end{pmatrix}
$$

Первый шаг дает коэффициенты ${m}_{i1} = (2, 3, 4)$. Второй шаг дает коэффициенты ${m}_{i2} = (5, 6)$. Третий шаг дает ${m}_{i3} = (7)$, поэтому L-матрица будет следующей:

$$ L = \begin{pmatrix} 1 & 0 & 0 & 0 \\ 2 & 1 & 0 & 0 \\ 3 & 5 & 1 & 0 \\ 4 & 6 & 7 & 1 \end{pmatrix} $$

__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

Выпишем основную матрицу СЛАУ:

$$ A = \begin{pmatrix} 2 & 1 & 3 \\ 11 & 7 & 5 \\ 9 & 8 & 4 \end{pmatrix} $$

Найдем ее LU-разложение:
$$ \begin{pmatrix} 2 & 1 & 3 \\ 11 & 7 & 5 \\ 9 & 8 & 4 \end{pmatrix} \equiv 
\begin{pmatrix} 2 & 1 & 3 \\ 0 & 1.5 & -11.5 \\ 0 & 3.5 & -9.5 \end{pmatrix} \equiv
\begin{pmatrix} 2 & 1 & 3 \\ 0 & 1.5 & -11.5 \\ 0 & 0 & 52/3 \end{pmatrix} = U $$

$$ L = \begin{pmatrix} 1 & 0 & 0 \\ 5.5 & 1 & 0 \\ 4.5 & 7/3 & 1 \end{pmatrix} $$

$$ L y = b \implies y_1 = 1, y_2 = -5.5 y_1 - 6 = -11.5, y_3 = -4.5 y_1 -7/3 y_2 - 5 = 52/3 $$

$$ U x = y \implies x_3 = 1, x_2 = (11.5 x_3 - 11.5)/1.5 = 0, x_1 = (-x_2 - 3 x_3 + 1) / 2 = -1 $$

Значит,
$$ \vec{x} = (-1, 0, 1) $$

__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

$$ {l}_{11} = \sqrt{{a}_{11}} = \sqrt{81} = 9 $$

$$ {l}_{21} = {a}_{21} / {l}_{11} = -45/9 = -5 $$

$$ {l}_{31} = {a}_{31} / {l}_{11} = 45/9 = 5 $$

$$ {l}_{22} = \sqrt{{a}_{22} - {l}_{21}^2} = \sqrt{50 - 25} = 5 $$

$$ {l}_{32} = \frac{{a}_{32} - {l}_{31} {l}_{21}}{{l}_{22}} = \frac{-15 + 5 \cdot 5}{5} = 2 $$

$$ {l}_{33} = \sqrt{{a}_{33} - {l}_{31}^2 - {l}_{32}^2} = \sqrt{38 - 25 - 4} = 3 $$

Таким образом, L-матрица равна

$$ L = \begin{pmatrix} 9 & 0 & 0 \\ -5 & 5 & 0 \\ 5 & 2 & 3 \end{pmatrix} $$

а ее транспонированная версия

$$ L^T = \begin{pmatrix} 9 & -5 & 5 \\ 0 & 5 & 2 \\ 0 & 0 & 3 \end{pmatrix} $$

Решим систему $L y = b$

$$y_1 = 531 / 9 = 59 $$

$$y_2 = (5 y_1 - 460) / 5 = -33 $$

$$y_3 = (-5 y_1 - 2 y_2 + 193) / 3 = -12 $$

Решим систему $L^T x = y$

$$ x_3 = y_3 / 3 = -12 / 3 = -4 $$

$$ x_2 = (-2 x_3 - 33 ) / 5 = -25 / 5 = -5 $$

$$ x_1 = (5 x_2 - 5 x_3 + 59 ) / 9 = 54 / 9 = 6 $$

Таким образом $$ \vec{x} = (6, -5, -4) $$

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [143]:
import numpy as np
np.set_printoptions(suppress=True)

def lu_solver(A, b):
    assert A.shape[0] == A.shape[1]
    assert A.shape[1] == b.shape[0]
    imax = np.argmax(np.abs(A[:, 0]))
    if imax > 0:
        tmp = A[0, :].copy()
        A[0, :] = A[imax, :]
        A[imax, :] = tmp.copy()
        tmp = b[0]
        b[0] = b[imax]
        b[imax] = tmp
    assert A[0][0] != 0
    L = np.eye(A.shape[0], dtype = 'double')
    U = A.astype('double')
    for j in range(A.shape[0]):
        for i in range(j + 1, A.shape[0]):
            L[i][j] = U[i][j] / U[j][j]
            for k in range(A.shape[1]):
                U[i][k] = U[i][k] - U[j][k] * L[i][j]
    # Ly = b
    y = np.zeros(b.shape)
    for i in range(A.shape[0]):
        y[i] = b[i] - np.dot(L[i][0:i], y[0:i])
    # Ux = y
    x = np.zeros(b.shape)
    for i in range(A.shape[0] - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i][i + 1:], x[i + 1:])) / U[i][i]
    
    return [x, L, U]

A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])
solution = lu_solver(A, b)

x, L, U = solution

In [144]:
print(A)

[[11  7  5]
 [ 2  1  3]
 [ 9  8  4]]


In [145]:
print('Решение СЛАУ: x = ')
print(x)

Решение СЛАУ: x = 
[-1. -0.  1.]


In [146]:
print('L = ')
print(L)

L = 
[[ 1.          0.          0.        ]
 [ 0.18181818  1.          0.        ]
 [ 0.81818182 -8.33333333  1.        ]]


In [147]:
print('U = ')
print(U)

U = 
[[11.          7.          5.        ]
 [ 0.         -0.27272727  2.09090909]
 [ 0.         -0.         17.33333333]]


In [148]:
print('L2 error test')
error = (A.dot(x) - b)
l2 = np.sqrt(error.dot(np.conj(error)))
print(l2)

L2 error test
0.0
